### ISSUE TITLE
 错误: 找不到符号

### ISSUE THREAD

**Issue by iamyuzhe** [alighters/AndroidDemos#1]
Error:(70, 34) 错误: 找不到符号
符号:   方法 onHostPause(ToastRnActivity)
位置: 类型为ReactInstanceManager的变量 mReactInstanceManager

Error:(79, 34) 错误: 找不到符号
符号:   方法 onHostResume(ToastRnActivity,ToastRnActivity)
位置: 类型为ReactInstanceManager的变量 mReactInstanceManager

@alighters

**Comment by alighters** [comment]
@bruceyu1994 这个应该 react native 的版本与本地版本不一致的问题。你不需要这个的话，可以先注释掉，是没问题的。

**Comment by iamyuzhe** [comment]
可能是的吧，我把方法签名中的Host去掉，改成onPause()和onResume()就可以了

**Comment by alighters** [comment]
@bruceyu1994 嗯，是的。
