### ISSUE TITLE
Observable<ResponceInfo> postLogin(@Body MsgInfo msgInfo); 如果我的参数是body注解下的对象，如何解析呢？

### ISSUE THREAD

**Issue by zhengjieAdriod** [alighters/AndroidDemos#2]
请问是这样吗？
if(args[i] instanceof MsgInfo){
MsgInfo  info  = (MsgInfo) args[i];
 info.setToken("newToken");
}

**Comment by alighters** [comment]
对的，就是这个意思。通过判断参数类型，拿到指定的类型，进行 token 的更新

**Comment by zhengjieAdriod** [comment]
好的 谢谢
